"""OSVVM Scripts (.pro) helpers — Qt-free and unit-testable.

OSVVM project scripts (``.pro``) are TCL that use the OSVVM API after
``source …/Scripts/StartUp.tcl``. Typical batch flow::

    tclsh
    source /path/to/OsvvmLibraries/Scripts/StartUp.tcl
    build /path/to/project.pro
    exit

See https://github.com/OSVVM/OSVVM-Scripts
"""

from __future__ import annotations

import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path

MODE_NORMAL = "normal"
MODE_OSVVM = "osvvm"
STUDIO_MODES = (MODE_NORMAL, MODE_OSVVM)

STARTUP_TCL_NAME = "StartUp.tcl"

# Default HTML report path relative to the directory that contains the .pro
# file (common OSVVM project layout). Override in Settings.
DEFAULT_OSVVM_HTML_REPORT = "build_all/build_all.html"


def find_tclsh_executable() -> str | None:
    """Return the path to ``tclsh`` (or ``tclsh86`` / ``tclsh8.6``) if on PATH."""
    for name in ("tclsh", "tclsh8.6", "tclsh86", "tclsh8.5"):
        found = shutil.which(name)
        if found:
            return found
    return None


def tcl_quote(path: str) -> str:
    """Quote a filesystem path for safe use inside a TCL script."""
    normalised = path.replace("\\", "/")
    escaped = normalised.replace("{", "\\{").replace("}", "\\}")
    return "{" + escaped + "}"


def resolve_startup_tcl(scripts_or_libraries_path: str) -> Path | None:
    """Locate ``StartUp.tcl`` under an OSVVM Scripts or OsvvmLibraries path.

    Accepts either the ``Scripts`` directory itself or the parent
    ``OsvvmLibraries`` (or similar) root that contains ``Scripts/StartUp.tcl``.
    """
    raw = (scripts_or_libraries_path or "").strip()
    if not raw:
        return None
    base = Path(raw).expanduser()
    candidates = [
        base / STARTUP_TCL_NAME,
        base / "Scripts" / STARTUP_TCL_NAME,
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    return None


def is_pro_file(path: str) -> bool:
    """Return True for OSVVM project script files (``.pro``)."""
    return Path(path).suffix.lower() == ".pro"


def resolve_osvvm_html_report(
    pro_file: str,
    report_path: str | None = None,
) -> Path:
    """Resolve the OSVVM HTML report path for a ``.pro`` session.

    Relative ``report_path`` values are resolved against the directory that
    contains ``pro_file``. Absolute paths are returned as-is. Empty
    ``report_path`` uses :data:`DEFAULT_OSVVM_HTML_REPORT`.
    """
    configured = (report_path or "").strip() or DEFAULT_OSVVM_HTML_REPORT
    candidate = Path(configured).expanduser()
    if candidate.is_absolute():
        return candidate
    base = Path(pro_file).expanduser().resolve().parent
    return (base / candidate).resolve()


def build_osvvm_batch_script(startup_tcl: str, pro_file: str) -> str:
    """Return TCL source that loads OSVVM Scripts and builds a ``.pro`` file.

    ``build`` may raise after a successful simulate when HTML/YAML index
    reports fail (OSVVM Scripts quirk, e.g. missing dict key ``Passed``).
    This wrapper treats analyze/simulate error counts as the real status and
    exits 0 when those are zero so GHDL Studio can open waveforms.
    """
    if not startup_tcl:
        raise ValueError("OSVVM StartUp.tcl path is required.")
    if not pro_file:
        raise ValueError("A .pro file path is required.")
    startup_q = tcl_quote(str(Path(startup_tcl).resolve()))
    pro_q = tcl_quote(str(Path(pro_file).resolve()))
    return f"""# Generated by GHDL Studio — do not edit
source {startup_q}
# Do not fail the process solely because HTML/YAML reports misbehave.
if {{[info exists ::osvvm::FailOnReportErrors]}} {{
  set ::osvvm::FailOnReportErrors false
}}
set _ghdlStudioBuildRc [catch {{build {pro_q}}} _ghdlStudioBuildMsg]
set _ghdlStudioAnalyzeErr 0
set _ghdlStudioSimulateErr 0
if {{[info exists ::osvvm::AnalyzeErrorCount]}} {{
  set _ghdlStudioAnalyzeErr $::osvvm::AnalyzeErrorCount
}}
if {{[info exists ::osvvm::SimulateErrorCount]}} {{
  set _ghdlStudioSimulateErr $::osvvm::SimulateErrorCount
}}
if {{[info exists ::osvvm::BuildStatus]}} {{
  puts "GHDL Studio: BuildStatus=$::osvvm::BuildStatus AnalyzeErrors=$_ghdlStudioAnalyzeErr SimulateErrors=$_ghdlStudioSimulateErr"
}}
if {{$_ghdlStudioAnalyzeErr > 0 || $_ghdlStudioSimulateErr > 0}} {{
  puts "GHDL Studio: build failed (analyze/simulate errors)."
  if {{$_ghdlStudioBuildRc}} {{
    puts $_ghdlStudioBuildMsg
  }}
  exit 1
}}
if {{$_ghdlStudioBuildRc}} {{
  puts "GHDL Studio: analyze/simulate OK; ignoring post-build report error:"
  puts $_ghdlStudioBuildMsg
}}
exit 0
"""


@dataclass(frozen=True)
class OsvvmRunPlan:
    """Everything needed to launch ``tclsh`` for an OSVVM ``.pro`` build."""

    tclsh: str
    script_path: str
    cwd: str
    command_display: str


def prepare_osvvm_run(
    *,
    tclsh: str,
    startup_tcl: str,
    pro_file: str,
    script_dir: str | None = None,
) -> OsvvmRunPlan:
    """Write a temporary batch TCL script and return the run plan.

    ``cwd`` is the directory containing the ``.pro`` file so relative includes
    and GHDL work directories behave like a manual OSVVM Scripts session.
    """
    pro_path = Path(pro_file).resolve()
    if not pro_path.is_file():
        raise FileNotFoundError(f".pro file not found: {pro_file}")
    startup = Path(startup_tcl).resolve()
    if not startup.is_file():
        raise FileNotFoundError(f"StartUp.tcl not found: {startup_tcl}")
    if not tclsh:
        raise ValueError("tclsh executable is required.")

    content = build_osvvm_batch_script(str(startup), str(pro_path))
    directory = script_dir or tempfile.gettempdir()
    Path(directory).mkdir(parents=True, exist_ok=True)
    script_file = Path(directory) / "ghdl_studio_osvvm_run.tcl"
    script_file.write_text(content, encoding="utf-8")

    return OsvvmRunPlan(
        tclsh=tclsh,
        script_path=str(script_file.resolve()),
        cwd=str(pro_path.parent),
        command_display=f"{tclsh} {script_file.resolve()}  # build {pro_path.name}",
    )


def find_recent_waveform(
    search_root: str,
    *,
    newer_than_mtime: float | None = None,
) -> str | None:
    """Find the newest ``.ghw`` / ``.vcd`` under ``search_root`` (shallow walk).

    Prefers ``.ghw`` when timestamps are equal. Used after an OSVVM ``build``
    to open waveforms in Surfer / the internal viewer when present.
    """
    root = Path(search_root)
    if not root.is_dir():
        return None

    best: Path | None = None
    best_mtime = -1.0
    for pattern in ("**/*.ghw", "**/*.vcd"):
        for candidate in root.glob(pattern):
            if not candidate.is_file():
                continue
            try:
                mtime = candidate.stat().st_mtime
            except OSError:
                continue
            if newer_than_mtime is not None and mtime < newer_than_mtime:
                continue
            if mtime > best_mtime or (
                mtime == best_mtime
                and best is not None
                and candidate.suffix.lower() == ".ghw"
                and best.suffix.lower() != ".ghw"
            ):
                best = candidate
                best_mtime = mtime
    return str(best.resolve()) if best is not None else None
